[ci] Create an issue when loadtests fails (#47378)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

Adds a `notify-failure` job that creates a GitHub issue when load tests
fail. Includes dedup check, performance results table, test failure
output, and failed job names.

Load tests are currently failing and will be fixed in another
[PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/47385).

<!-- Issue number (e.g. #1234) or full URL to issue, if applicable. -->
#### Link to tracking issue
Relates to #46670

<!--Describe what testing was performed and which tests were added.-->
#### Testing

Tested locally against a real failed run (run ID 23989057509).

<details>
<summary>Sample issue body output</summary>

Auto-generated report for load-tests workflow.

Link to failed build:
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/23989057509
Commit:
[90753d1](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/90753d15fe1f2a4bcebd83ed17016e72f7288817)

### Component(s)

testbed

### Failed jobs

- loadtest (TestTraceNoBackend10kSPS|TestTrace1kSPSWithAttrs)

### Performance results

```
# Test PerformanceResults
Started: Sat, 04 Apr 2026 22:43:51 +0000

Test                                    |Result|Duration|CPU Avg%|CPU Max%|CPU Limit|RAM Avg MiB|RAM Max MiB|RAM Limit MiB|Sent Items|Received Items|
----------------------------------------|------|-------:|-------:|-------:|--------:|----------:|----------:|------------:|---------:|-------------:|
TraceNoBackend10kSPS/NoMemoryLimit      |FAIL  |     13s|   120.6|   121.0|     0.0|         45|         96|          0|     22600|         22590|CPU consumption is 121.0%, max expected is 90%
TraceNoBackend10kSPS/MemoryLimit        |FAIL  |     23s|   113.6|   113.6|     0.0|         33|         97|          0|     18510|         18490|CPU consumption is 113.6%, max expected is 90%
Trace1kSPSWithAttrs/0*0bytes            |PASS  |     15s|    20.0|    23.0|     0.0|         66|         94|          0|     15000|         15000|
Trace1kSPSWithAttrs/100*50bytes         |PASS  |     15s|    56.2|    58.7|     0.0|         71|        100|          0|     14990|         14990|
Trace1kSPSWithAttrs/10*1000bytes        |PASS  |     15s|    40.0|    42.0|     0.0|         70|         99|          0|     14990|         14990|
Trace1kSPSWithAttrs/20*5000bytes        |PASS  |     15s|    51.9|    53.3|     0.0|         75|        105|          0|      1830|          1830|

Total duration: 97s
```

#### Test failures

```
--- FAIL: TestTraceNoBackend10kSPS (36.02s)
    --- FAIL: TestTraceNoBackend10kSPS/NoMemoryLimit (13.02s)
    --- FAIL: TestTraceNoBackend10kSPS/MemoryLimit (23.01s)
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/testbed/tests	97.421s
```

Note: Information about any subsequent build failures that happen while
this issue is open, will be added as comments with more information to
this issue.
</details>

---------

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>